# Generated by Django 3.2.22 on 2024-11-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0019_appointment_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientreg',
            old_name='patient',
            new_name='admin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc'), (3, 'patient')], default=1, max_length=50),
        ),
    ]
