# Generated by Django 3.2.22 on 2024-11-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0020_auto_20241121_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='specialization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dasapp.specialization'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin'), (3, 'patient')], default=1, max_length=50),
        ),
    ]
