# Generated by Django 3.2.22 on 2024-11-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0021_auto_20241121_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='consultation_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorreg',
            name='consultation_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorreg',
            name='dalily_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (3, 'patient'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
