# Generated by Django 3.2.22 on 2024-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0022_auto_20241122_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_of_appointment',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'patient'), (1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
