# Generated by Django 3.2.22 on 2024-11-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0023_auto_20241122_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_of_appointment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc'), (3, 'patient')], default=1, max_length=50),
        ),
    ]
