# Generated by Django 3.2.22 on 2024-11-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0024_auto_20241122_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin'), (3, 'patient')], default=1, max_length=50),
        ),
    ]
