# Generated by Django 3.2.22 on 2024-11-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0025_auto_20241122_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='consultation_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'patient'), (2, 'doc'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
