# Generated by Django 3.2.22 on 2024-11-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0026_auto_20241123_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'patient'), (1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='consultation_fee',
            field=models.IntegerField(default=200),
        ),
    ]
