# Generated by Django 3.2.22 on 2024-11-23 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0027_auto_20241123_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (3, 'patient'), (1, 'admin')], default=1, max_length=50),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_no', models.CharField(max_length=50)),
                ('expiry', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=5)),
                ('pincode', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('admin_share', models.FloatField()),
                ('doctor_share', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dasapp.appointment')),
            ],
        ),
    ]
