# Generated by Django 3.2.22 on 2024-11-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0028_auto_20241123_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='recommendedtest',
            new_name='findings',
        ),
    ]
